-- The Dataset that I use in this project was downloaded from Gregory Smith's Kaggle page, generated by a scrape of vgchartz.com
-- In this project, i want to know the distribution of video games sales by some attributes.
-- I'd like to find out which video games genres and title/names have the best number of sales globally and regionally 

-- First, let's take a look at global sales grouped by the genre to see people's ost favourite games
SELECT 
    Genre,
    SUM(Global_Sales)
FROM
    vgsales
GROUP BY Genre
ORDER BY SUM(Global_Sales) DESC
;

-- From the result, we can see that video games with Action genre top the list, followed by Sports and Shooter
-- But, let's see the genre interests on each region (europe, japan, north america, and rest of the world)
-- * Europe
SELECT 
    Genre,
    SUM(EU_Sales)
FROM
    vgsales
GROUP BY Genre
ORDER BY SUM(EU_Sales) DESC
;
-- * North America
SELECT 
    Genre,
    SUM(NA_Sales)
FROM
    vgsales
GROUP BY Genre
ORDER BY SUM(NA_Sales) DESC
;
-- * Japan
SELECT 
    Genre,
    SUM(JP_Sales)
FROM
    vgsales
GROUP BY Genre
ORDER BY SUM(JP_Sales) DESC
;
-- * Rest of the world
SELECT 
    Genre,
    SUM(Other_Sales)
FROM
    vgsales
GROUP BY Genre
ORDER BY SUM(Other_Sales) DESC
;
-- The sales from most of the region supports the fact that those 3 genres top the list, except in Japan
-- Japan video game consumers prefer Role-playing games over Action and Sports, with the sales difference almost twice bigger than thse two

-- So, let's see the video games that included in those genres, but with more than 10 millions sales globally
SELECT 
    vg_name, 
    Genre,
    Global_Sales
FROM
    vgsales
WHERE Global_Sales >= 20
ORDER BY Global_Sales DESC;

-- Interestingly, from 20 video games that match our criteria, only 2 of them actually have Action genre, and stand at 17th and 18th position
-- Meanwhile, Wii Sports really lead the standings with twice as many sales as the second position, Super Mario Bros
-- We eant to see the sales contribution to Wii Sports, so let's include the regional sales in the query
SELECT 
    vg_name, 
    Genre,
    NA_Sales,
    EU_Sales,
    JP_Sales,
    Other_Sales
    Global_Sales
FROM
    vgsales
WHERE vg_name = 'Wii Sports'
;
-- According to the latest query result, we know the fact that North Americans contribute more than half of the sales for Wii Sports with over 41 millions
-- Last but not least, we want to see which video game publisher did the best in terms of sales
SELECT 
    Publisher,
    ROUND(SUM(Global_Sales),2),
    ROUND(SUM(NA_Sales),2),
    ROUND(SUM(EU_Sales),2),
    ROUND(SUM(JP_Sales),2),
    ROUND(SUM(Other_Sales),2)
FROM
    vgsales
GROUP BY Publisher
ORDER BY SUM(Global_Sales) DESC
;
-- The fact is Nintendo still lead the race as the best video game publisher with over than 1,7 billion of global sales, 
-- while they also top the list in North America, Europe and Japan.alter

-- That's all for this project. Thank you for checking it up until the end. Have a good day :)